name: Publish Firefox

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build
      run: |
        yarn
        yarn build:firefox
    - name: Upload & release
      uses: yayuyokitano/firefox-addon@v0.0.6-alpha
      with:
        api_key: ${{ secrets.AMO_ISSUER }}
        api_secret: ${{ secrets.AMO_SECRET }}
        guid: '{4015ef04-67e5-4166-8221-f2c731101288} '
        xpi_path: dist/bss-firefox.zip
        src_path: dist/bss-firefox-source.zip